// GENERATED by scripts/route-manifest.mjs (npm run routes:manifest). Do not edit by hand.
export type RouteKind = "index" | "utility" | "case-study" | "article" | "not-found";
export interface RouteEntry {
  path: string;
  kind: RouteKind;
  expectStatus: number;
}

export const ROUTES: RouteEntry[] = [
  {
    "path": "/",
    "kind": "index",
    "expectStatus": 200
  },
  {
    "path": "/about",
    "kind": "index",
    "expectStatus": 200
  },
  {
    "path": "/projects",
    "kind": "index",
    "expectStatus": 200
  },
  {
    "path": "/ai-pm",
    "kind": "index",
    "expectStatus": 200
  },
  {
    "path": "/blog",
    "kind": "index",
    "expectStatus": 200
  },
  {
    "path": "/contact",
    "kind": "index",
    "expectStatus": 200
  },
  {
    "path": "/now",
    "kind": "utility",
    "expectStatus": 200
  },
  {
    "path": "/lab",
    "kind": "index",
    "expectStatus": 200
  },
  {
    "path": "/uses",
    "kind": "utility",
    "expectStatus": 200
  },
  {
    "path": "/bookshelf",
    "kind": "utility",
    "expectStatus": 200
  },
  {
    "path": "/changelog",
    "kind": "utility",
    "expectStatus": 200
  },
  {
    "path": "/projects/aarchid",
    "kind": "case-study",
    "expectStatus": 200
  },
  {
    "path": "/projects/better-half",
    "kind": "case-study",
    "expectStatus": 200
  },
  {
    "path": "/projects/cohort-retention-studio",
    "kind": "case-study",
    "expectStatus": 200
  },
  {
    "path": "/projects/desktasks",
    "kind": "case-study",
    "expectStatus": 200
  },
  {
    "path": "/projects/experiment-hub",
    "kind": "case-study",
    "expectStatus": 200
  },
  {
    "path": "/projects/hackmate",
    "kind": "case-study",
    "expectStatus": 200
  },
  {
    "path": "/projects/kite-edge",
    "kind": "case-study",
    "expectStatus": 200
  },
  {
    "path": "/projects/portfolio-site",
    "kind": "case-study",
    "expectStatus": 200
  },
  {
    "path": "/projects/sawari",
    "kind": "case-study",
    "expectStatus": 200
  },
  {
    "path": "/projects/tcs-nqt-prep-hub",
    "kind": "case-study",
    "expectStatus": 200
  },
  {
    "path": "/blog/building-portfolio-as-product",
    "kind": "article",
    "expectStatus": 200
  },
  {
    "path": "/blog/choosing-a-product-without-ai",
    "kind": "article",
    "expectStatus": 200
  },
  {
    "path": "/blog/cohorts-before-dashboards",
    "kind": "article",
    "expectStatus": 200
  },
  {
    "path": "/blog/data-driven-product-decisions",
    "kind": "article",
    "expectStatus": 200
  },
  {
    "path": "/blog/designing-self-hosted-experimentation-platform",
    "kind": "article",
    "expectStatus": 200
  },
  {
    "path": "/blog/figma-to-live-parity-audit",
    "kind": "article",
    "expectStatus": 200
  },
  {
    "path": "/blog/metrics-that-matter-for-pms",
    "kind": "article",
    "expectStatus": 200
  },
  {
    "path": "/blog/one-year-of-pm-internships",
    "kind": "article",
    "expectStatus": 200
  },
  {
    "path": "/blog/privacy-contract-regression-suite",
    "kind": "article",
    "expectStatus": 200
  },
  {
    "path": "/blog/seventeen-checks-before-you-call-a-site-done",
    "kind": "article",
    "expectStatus": 200
  },
  {
    "path": "/blog/shipping-llm-products-eval-harness",
    "kind": "article",
    "expectStatus": 200
  },
  {
    "path": "/blog/structured-thinking-framework",
    "kind": "article",
    "expectStatus": 200
  },
  {
    "path": "/blog/the-prd-is-dead-long-live-the-eval-set",
    "kind": "article",
    "expectStatus": 200
  },
  {
    "path": "/blog/why-pms-should-code",
    "kind": "article",
    "expectStatus": 200
  },
  {
    "path": "/this-route-does-not-exist",
    "kind": "not-found",
    "expectStatus": 404
  }
];

/** Routes that were withdrawn and must 404 and appear nowhere. */
export const WITHDRAWN_ROUTES: string[] = ["/projects/churn-analysis"];

export const NOT_FOUND_PATH = "/this-route-does-not-exist";

export const routesOfKind = (kind: RouteKind): RouteEntry[] => ROUTES.filter((r) => r.kind === kind);

/** File-name slug used by screenshots and reports: "/" -> "home", "/a/b" -> "a_b". */
export const routeSlug = (p: string): string => (p === "/" ? "home" : p.slice(1).split("/").join("_"));
